# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    sres = 250

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 650))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.CaptureB = QtWidgets.QPushButton(self.centralWidget)
        self.CaptureB.setGeometry(QtCore.QRect(800, 30, 141, 31))
        self.CaptureB.setObjectName("CaptureB")
        self.ScanB = QtWidgets.QPushButton(self.centralWidget)
        self.ScanB.setGeometry(QtCore.QRect(610, 30, 131, 31))
        self.ScanB.setCheckable(True)
        self.ScanB.setObjectName("ScanB")
        self.XZoomGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.XZoomGroup.setGeometry(QtCore.QRect(570, 90, 401, 151))
        self.XZoomGroup.setTitle("")
        self.XZoomGroup.setObjectName("XZoomGroup")
        self.XResetB = QtWidgets.QPushButton(self.XZoomGroup)
        self.XResetB.setGeometry(QtCore.QRect(240, 110, 93, 28))
        self.XResetB.setObjectName("XResetB")
        self.XUpdateB = QtWidgets.QPushButton(self.XZoomGroup)
        self.XUpdateB.setGeometry(QtCore.QRect(56, 110, 121, 28))
        self.XUpdateB.setObjectName("XUpdateB")
        self.label_14 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_14.setGeometry(QtCore.QRect(234, 47, 16, 19))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.XScanLabel = QtWidgets.QLabel(self.XZoomGroup)
        self.XScanLabel.setGeometry(QtCore.QRect(80, 10, 241, 41))
        self.XScanLabel.setObjectName("XScanLabel")
        self.label_6 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_6.setGeometry(QtCore.QRect(154, 50, 27, 19))
        self.label_6.setObjectName("label_6")
        self.XZoomSlider = QtWidgets.QSlider(self.XZoomGroup)
        self.XZoomSlider.setGeometry(QtCore.QRect(70, 69, 271, 31))
        self.XZoomSlider.setMinimum(-6)
        self.XZoomSlider.setMaximum(0)
        self.XZoomSlider.setSingleStep(0)
        self.XZoomSlider.setPageStep(20)
        self.XZoomSlider.setProperty("value", -3)
        self.XZoomSlider.setSliderPosition(-3)
        self.XZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.XZoomSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.XZoomSlider.setTickInterval(1)
        self.XZoomSlider.setObjectName("XZoomSlider")
        self.label_12 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_12.setGeometry(QtCore.QRect(186, 47, 16, 19))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 27))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_8.setGeometry(QtCore.QRect(241, 50, 27, 19))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_3.setGeometry(QtCore.QRect(350, 70, 31, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_5.setGeometry(QtCore.QRect(326, 50, 27, 19))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_7.setGeometry(QtCore.QRect(70, 50, 27, 19))
        self.label_7.setObjectName("label_7")
        self.XZoomGroup_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.XZoomGroup_2.setGeometry(QtCore.QRect(570, 240, 401, 151))
        self.XZoomGroup_2.setTitle("")
        self.XZoomGroup_2.setObjectName("XZoomGroup_2")
        self.YResetB = QtWidgets.QPushButton(self.XZoomGroup_2)
        self.YResetB.setGeometry(QtCore.QRect(240, 110, 93, 28))
        self.YResetB.setObjectName("YResetB")
        self.YUpdateB = QtWidgets.QPushButton(self.XZoomGroup_2)
        self.YUpdateB.setGeometry(QtCore.QRect(56, 110, 121, 28))
        self.YUpdateB.setObjectName("YUpdateB")
        self.label_15 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_15.setGeometry(QtCore.QRect(234, 47, 16, 19))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.XScanLabel_2 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.XScanLabel_2.setGeometry(QtCore.QRect(80, 10, 241, 41))
        self.XScanLabel_2.setObjectName("XScanLabel_2")
        self.label_9 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_9.setGeometry(QtCore.QRect(154, 50, 27, 19))
        self.label_9.setObjectName("label_9")
        self.YZoomSlider = QtWidgets.QSlider(self.XZoomGroup_2)
        self.YZoomSlider.setGeometry(QtCore.QRect(70, 69, 271, 31))
        self.YZoomSlider.setMinimum(-6)
        self.YZoomSlider.setMaximum(0)
        self.YZoomSlider.setSingleStep(0)
        self.YZoomSlider.setPageStep(20)
        self.YZoomSlider.setProperty("value", -3)
        self.YZoomSlider.setSliderPosition(-3)
        self.YZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.YZoomSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.YZoomSlider.setTickInterval(1)
        self.YZoomSlider.setObjectName("YZoomSlider")
        self.label_16 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_16.setGeometry(QtCore.QRect(186, 47, 16, 19))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_4 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 61, 27))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_10.setGeometry(QtCore.QRect(241, 50, 27, 19))
        self.label_10.setObjectName("label_10")
        self.label_17 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_17.setGeometry(QtCore.QRect(350, 70, 31, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_18.setGeometry(QtCore.QRect(326, 50, 27, 19))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.XZoomGroup_2)
        self.label_19.setGeometry(QtCore.QRect(70, 50, 27, 19))
        self.label_19.setObjectName("label_19")
        self.XZoomGroup_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.XZoomGroup_3.setGeometry(QtCore.QRect(570, 390, 401, 151))
        self.XZoomGroup_3.setTitle("")
        self.XZoomGroup_3.setObjectName("XZoomGroup_3")
        self.RResetB = QtWidgets.QPushButton(self.XZoomGroup_3)
        self.RResetB.setGeometry(QtCore.QRect(240, 110, 93, 28))
        self.RResetB.setObjectName("RResetB")
        self.RUpdateB = QtWidgets.QPushButton(self.XZoomGroup_3)
        self.RUpdateB.setGeometry(QtCore.QRect(56, 110, 121, 28))
        self.RUpdateB.setObjectName("RUpdateB")
        self.label_29 = QtWidgets.QLabel(self.XZoomGroup_3)
        self.label_29.setGeometry(QtCore.QRect(234, 47, 16, 19))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.XScanLabel_4 = QtWidgets.QLabel(self.XZoomGroup_3)
        self.XScanLabel_4.setGeometry(QtCore.QRect(80, 10, 241, 41))
        self.XScanLabel_4.setObjectName("XScanLabel_4")
        self.label_32 = QtWidgets.QLabel(self.XZoomGroup_3)
        self.label_32.setGeometry(QtCore.QRect(186, 47, 16, 19))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.XRes = QtWidgets.QSpinBox(self.XZoomGroup_3)
        self.XRes.setGeometry(QtCore.QRect(100, 50, 91, 41))
        self.XRes.setAccelerated(True)
        self.XRes.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.XRes.setMinimum(200)
        self.XRes.setMaximum(500)
        self.XRes.setSingleStep(5)
        self.XRes.setProperty("value", self.sres)
        self.XRes.setObjectName("XRes")
        self.label = QtWidgets.QLabel(self.XZoomGroup_3)
        self.label.setGeometry(QtCore.QRect(70, 50, 21, 41))
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.XZoomGroup_3)
        self.label_11.setGeometry(QtCore.QRect(230, 50, 21, 41))
        self.label_11.setObjectName("label_11")
        self.YRes = QtWidgets.QSpinBox(self.XZoomGroup_3)
        self.YRes.setGeometry(QtCore.QRect(260, 50, 91, 41))
        self.YRes.setAccelerated(True)
        self.YRes.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.YRes.setMinimum(200)
        self.YRes.setMaximum(500)
        self.YRes.setSingleStep(5)
        self.YRes.setProperty("value", self.sres)
        self.YRes.setObjectName("YRes")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CaptureB.setText(_translate("MainWindow", "Capture Image"))
        self.ScanB.setText(_translate("MainWindow", "Scan"))
        self.XResetB.setText(_translate("MainWindow", "Reset"))
        self.XUpdateB.setText(_translate("MainWindow", "Update Scan"))
        self.XScanLabel.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p>Change zoom level across horizontal axis.</p></body></html>"))
        self.XScanLabel.setText(_translate("MainWindow",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#00007f;\">X-Scan Zoom Level</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-2</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">3</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">mV</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-1</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">3</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">V</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">0</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-3</span></p></body></html>"))
        self.YResetB.setText(_translate("MainWindow", "Reset"))
        self.YUpdateB.setText(_translate("MainWindow", "Update Scan"))
        self.XScanLabel_2.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Change zoom level across vertical axis.</p></body></html>"))
        self.XScanLabel_2.setText(_translate("MainWindow",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#00007f;\">Y-Scan Zoom Level</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-2</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">3</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">mV</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-1</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">3</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">V</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">0</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-3</span></p></body></html>"))
        self.RResetB.setText(_translate("MainWindow", "Reset"))
        self.RUpdateB.setText(_translate("MainWindow", "Update Scan"))
        self.XScanLabel_4.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Change resolution (size) of image</p></body></html>"))
        self.XScanLabel_4.setText(_translate("MainWindow",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#00007f;\">Resolution Level (pix)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:18pt;\">X</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:18pt;\">Y</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
