# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 650))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.CaptureB = QtWidgets.QPushButton(self.centralWidget)
        self.CaptureB.setGeometry(QtCore.QRect(800, 50, 141, 31))
        self.CaptureB.setObjectName("CaptureB")
        self.ScanB = QtWidgets.QPushButton(self.centralWidget)
        self.ScanB.setGeometry(QtCore.QRect(630, 50, 131, 31))
        self.ScanB.setCheckable(True)
        self.ScanB.setObjectName("ScanB")
        self.scanArea = QtWidgets.QLabel(self.centralWidget)
        self.scanArea.setGeometry(QtCore.QRect(50, 50, 500, 500))
        self.scanArea.setMinimumSize(QtCore.QSize(500, 500))
        self.scanArea.setObjectName("scanArea")
        self.RefreshLabel = QtWidgets.QLabel(self.centralWidget)
        self.RefreshLabel.setGeometry(QtCore.QRect(620, 478, 161, 31))
        self.RefreshLabel.setObjectName("RefreshLabel")
        self.refreshRate = QtWidgets.QSpinBox(self.centralWidget)
        self.refreshRate.setGeometry(QtCore.QRect(780, 482, 45, 25))
        self.refreshRate.setAccelerated(True)
        self.refreshRate.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.refreshRate.setKeyboardTracking(True)
        self.refreshRate.setMinimum(10)
        self.refreshRate.setMaximum(60)
        self.refreshRate.setObjectName("refreshRate")
        self.ref_secondsT = QtWidgets.QLabel(self.centralWidget)
        self.ref_secondsT.setGeometry(QtCore.QRect(840, 481, 71, 24))
        self.ref_secondsT.setObjectName("ref_secondsT")
        self.XZoomGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.XZoomGroup.setGeometry(QtCore.QRect(590, 100, 381, 171))
        self.XZoomGroup.setTitle("")
        self.XZoomGroup.setObjectName("XZoomGroup")
        self.XResetB = QtWidgets.QPushButton(self.XZoomGroup)
        self.XResetB.setGeometry(QtCore.QRect(230, 130, 93, 28))
        self.XResetB.setObjectName("XResetB")
        self.XUpdateB = QtWidgets.QPushButton(self.XZoomGroup)
        self.XUpdateB.setGeometry(QtCore.QRect(60, 130, 97, 28))
        self.XUpdateB.setObjectName("XUpdateB")
        self.label_14 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_14.setGeometry(QtCore.QRect(234, 67, 16, 19))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_11.setGeometry(QtCore.QRect(138, 67, 16, 19))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.XScanLabel = QtWidgets.QLabel(self.XZoomGroup)
        self.XScanLabel.setGeometry(QtCore.QRect(52, 23, 309, 36))
        self.XScanLabel.setObjectName("XScanLabel")
        self.label_6 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_6.setGeometry(QtCore.QRect(210, 67, 27, 19))
        self.label_6.setObjectName("label_6")
        self.XScanZoom = QtWidgets.QSlider(self.XZoomGroup)
        self.XScanZoom.setGeometry(QtCore.QRect(60, 93, 271, 27))
        self.XScanZoom.setMinimum(-12)
        self.XScanZoom.setMaximum(-2)
        self.XScanZoom.setSingleStep(1)
        self.XScanZoom.setPageStep(20)
        self.XScanZoom.setProperty("value", -7)
        self.XScanZoom.setSliderPosition(-7)
        self.XScanZoom.setOrientation(QtCore.Qt.Horizontal)
        self.XScanZoom.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.XScanZoom.setTickInterval(1)
        self.XScanZoom.setObjectName("XScanZoom")
        self.label_12 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_12.setGeometry(QtCore.QRect(186, 67, 16, 19))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_2.setGeometry(QtCore.QRect(10, 91, 37, 27))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_9.setGeometry(QtCore.QRect(110, 67, 32, 19))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_4.setGeometry(QtCore.QRect(60, 67, 32, 19))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_8.setGeometry(QtCore.QRect(260, 67, 27, 19))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_3.setGeometry(QtCore.QRect(340, 93, 35, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_5.setGeometry(QtCore.QRect(310, 67, 27, 19))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.XZoomGroup)
        self.label_7.setGeometry(QtCore.QRect(160, 67, 27, 19))
        self.label_7.setObjectName("label_7")
        self.YZoomGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.YZoomGroup.setGeometry(QtCore.QRect(590, 290, 381, 171))
        self.YZoomGroup.setTitle("")
        self.YZoomGroup.setObjectName("YZoomGroup")
        self.XResetB_2 = QtWidgets.QPushButton(self.YZoomGroup)
        self.XResetB_2.setGeometry(QtCore.QRect(230, 130, 93, 28))
        self.XResetB_2.setObjectName("XResetB_2")
        self.XUpdateB_2 = QtWidgets.QPushButton(self.YZoomGroup)
        self.XUpdateB_2.setGeometry(QtCore.QRect(60, 130, 97, 28))
        self.XUpdateB_2.setObjectName("XUpdateB_2")
        self.label_15 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_15.setGeometry(QtCore.QRect(234, 67, 16, 19))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_13.setGeometry(QtCore.QRect(138, 67, 16, 19))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.XScanLabel_2 = QtWidgets.QLabel(self.YZoomGroup)
        self.XScanLabel_2.setGeometry(QtCore.QRect(52, 23, 309, 36))
        self.XScanLabel_2.setObjectName("XScanLabel_2")
        self.label_10 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_10.setGeometry(QtCore.QRect(210, 67, 27, 19))
        self.label_10.setObjectName("label_10")
        self.XScanZoom_2 = QtWidgets.QSlider(self.YZoomGroup)
        self.XScanZoom_2.setGeometry(QtCore.QRect(60, 93, 271, 27))
        self.XScanZoom_2.setMinimum(-12)
        self.XScanZoom_2.setMaximum(-2)
        self.XScanZoom_2.setSingleStep(1)
        self.XScanZoom_2.setPageStep(20)
        self.XScanZoom_2.setProperty("value", -7)
        self.XScanZoom_2.setSliderPosition(-7)
        self.XScanZoom_2.setOrientation(QtCore.Qt.Horizontal)
        self.XScanZoom_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.XScanZoom_2.setTickInterval(1)
        self.XScanZoom_2.setObjectName("XScanZoom_2")
        self.label_16 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_16.setGeometry(QtCore.QRect(186, 67, 16, 19))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_17.setGeometry(QtCore.QRect(10, 91, 37, 27))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_18.setGeometry(QtCore.QRect(110, 67, 32, 19))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_19.setGeometry(QtCore.QRect(60, 67, 32, 19))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_20.setGeometry(QtCore.QRect(260, 67, 27, 19))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_21.setGeometry(QtCore.QRect(340, 93, 35, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_22.setGeometry(QtCore.QRect(310, 67, 27, 19))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.YZoomGroup)
        self.label_23.setGeometry(QtCore.QRect(160, 67, 27, 19))
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.scanPixmap = QtGui.QPixmap('Yellow_BG.JPG')

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CaptureB.setText(_translate("MainWindow", "Capture Image"))
        self.ScanB.setText(_translate("MainWindow", "Scan"))
        self.scanArea.setPixmap(self.scanPixmap)
        self.RefreshLabel.setToolTip(_translate("MainWindow",
                                                "<html><head/><body><p>Change the time it takes for a full image refresh. Longer time ensures higher accuracy and less noise.</p></body></html>"))
        self.RefreshLabel.setText(_translate("MainWindow",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#00007f;\">Refresh Rate: </span></p></body></html>"))
        self.ref_secondsT.setText(_translate("MainWindow",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">seconds</span></p></body></html>"))
        self.XResetB.setText(_translate("MainWindow", "Reset"))
        self.XUpdateB.setText(_translate("MainWindow", "Update Scan"))
        self.XScanLabel.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p>Change zoom level across horizontal axis.</p></body></html>"))
        self.XScanLabel.setText(_translate("MainWindow",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#00007f;\">X-Scan Zoom Level (m)</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-6</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">1</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">pm</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-10</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-12</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-4</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">1</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">cm</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-2</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p>10<span style=\" vertical-align:super;\">-8</span></p></body></html>"))
        self.XResetB_2.setText(_translate("MainWindow", "Reset"))
        self.XUpdateB_2.setText(_translate("MainWindow", "Update Scan"))
        self.XScanLabel_2.setToolTip(_translate("MainWindow",
                                                "<html><head/><body><p>Change zoom level across horizontal axis.</p></body></html>"))
        self.XScanLabel_2.setText(_translate("MainWindow",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#00007f;\">Y-Scan Zoom Level (m)</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-6</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">1</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">pm</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-10</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-12</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-4</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">1</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">cm</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-2</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow",
                                         "<html><head/><body><p>10<span style=\" vertical-align:super;\">-8</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
